### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by aadrian** [nus/gitbucket-plantuml-plugin#10]
Please merge https://github.com/nus/gitbucket-plantuml-plugin/pull/9 and release 1.2.0

Thank you.

**Comment by nus** [comment]
Meged #12 and #13 and released 1.2.0
https://github.com/nus/gitbucket-plantuml-plugin/releases/tag/v1.2.0

**Comment by aadrian** [comment]
@nus Thank you for the release.
