### ISSUE TITLE
Want a release with newer plantuml

### ISSUE THREAD

**Issue by umq** [nus/gitbucket-plantuml-plugin#19]
The latest version is now more than one year old, some new features are not supported.
#17 is outdated, too.
is there any plan to make a release with newer plantuml?

btw, there's an [entry](https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml/1.2018.6#sbt) at MvnRepository, we might be able to remove jar binary from this repo.
The latest version in [maven-metadata](https://oss.sonatype.org/content/repositories/releases/net/sourceforge/plantuml/plantuml/maven-metadata.xml) is not correct, though.

**Comment by aadrian** [comment]
@umq the patch I submitted a log time ago was still not merged :( .

**Comment by nus** [comment]
[v1.4.0](https://github.com/nus/gitbucket-plantuml-plugin/releases/tag/v1.4.0) released!

**Comment by aadrian** [comment]
@nus thanks!
