### ISSUE TITLE
Update to latest PlantUML V1.2019.11

### ISSUE THREAD

**Issue by aadrian** [nus/gitbucket-plantuml-plugin#24]
Hi,

Please Update to latest PlantUML V1.2019.11
Especially useful PlantUML feature for upgrade: http://plantuml.com/style-evolution  :) 

Thank you.

**Comment by nus** [comment]
Thanks your request.
Released v1.6.1 with PlantUML v1.2019.11!
https://github.com/nus/gitbucket-plantuml-plugin/releases/tag/v1.6.1

**Comment by aadrian** [comment]
@nus Thank you for the release!
