### ISSUE TITLE
plugin 1.1.0 does not work with Gist plugin 4.7.0

### ISSUE THREAD

**Issue by shiena** [nus/gitbucket-plantuml-plugin#8]
OK: plugin 1.0.0 + Gitbucket 4.10.0 (user repository)
OK: plugin 1.0.0 + Gitbucket 4.10.0 + Gist plugin 4.6.0 (gist)
OK: plugin 1.0.0 + Gitbucket 4.11.0 (user repository)
OK: plugin 1.0.0 + Gitbucket 4.11.0 + Gist plugin 4.7.0 (gist)
OK: plugin 1.1.0 + Gitbucket 4.11.0 (user repository)
NG: plugin 1.1.0 + Gitbucket 4.11.0 + Gist plugin 4.7.0 (gist)

![image](https://cloud.githubusercontent.com/assets/1295639/24666399/2fda7d6c-199b-11e7-9ea8-d4faf4e00345.png)

**Comment by nus** [comment]
Thanks.

I release version 1.1.1 for resolving this issues. Let me known about version 1.1.1.

**Comment by shiena** [comment]
Thank you.
But it is another matter.

The UML is not drawn in the following steps.

1. Install Gist Plugin
2. Open Snippets in the header menu
3. Create a new Snippets
4. Create a new file foo.pu

The URL of foo.pu is  http://localhost:8080/root/999787cb6bd1a27de1297691642f2df4/plantuml/master/foo.pu

![2017-04-06_22h52_07](https://cloud.githubusercontent.com/assets/1295639/24758328/04c09ea8-1b1d-11e7-89b5-f3b0e872ab25.png)

**Comment by nus** [comment]
@shiena 

Could you try on commit f12ef41577594c49a0873d82f8f934a30ea6b462 ?

**Comment by shiena** [comment]
@nus 
Thanks! https://github.com/nus/gitbucket-plantuml-plugin/commit/f12ef41577594c49a0873d82f8f934a30ea6b462 worked fine with Gist plugin.

**Comment by nus** [comment]
I returned rendering method to version 1.0.0 .

**Comment by nus** [comment]
I'm glad to hear that!
